name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  cache_qt:
    strategy:
      fail-fast: true

    runs-on: windows-latest

    steps:
    - run: mkdir -p ${{ github.workspace }}/Qt

    - name: Cache Qt
      id: qt-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/Qt/6.7.0/msvc2019_64
        key: qt-cache-6.7.0-msvc2019_64-v1

    - working-directory: ${{ github.workspace }}/Qt
      run: curl --fail --retry 3 -L -o aqt_x64.exe https://github.com/miurahr/aqtinstall/releases/download/v3.1.12/aqt_x64.exe
      if: steps.qt-cache.outputs.cache-hit != 'true'

    - working-directory: ${{ github.workspace }}/Qt
      run: .\aqt_x64.exe install-qt windows desktop 6.7.0 win64_msvc2019_64
      if: steps.qt-cache.outputs.cache-hit != 'true'
